"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(BASE_DIR / '.env')

# Load Centralized Application Configuration System
from . import app_config

APP_NAME = app_config.APP_NAME
APP_VERSION = app_config.APP_VERSION
API_VERSION = app_config.API_VERSION
SUPPORTED_EMAIL_DOMAIN = app_config.SUPPORTED_EMAIL_DOMAIN
DEFAULT_TIMEZONE = app_config.DEFAULT_TIMEZONE

OTP_EXPIRY_MINUTES = app_config.OTP_EXPIRY_MINUTES
OTP_LENGTH = app_config.OTP_LENGTH
MAX_LOGIN_ATTEMPTS = app_config.MAX_LOGIN_ATTEMPTS
ACCOUNT_LOCK_DURATION_MINUTES = app_config.ACCOUNT_LOCK_DURATION_MINUTES
RESEND_OTP_DELAY_SECONDS = app_config.RESEND_OTP_DELAY_SECONDS
PASSWORD_RESET_EXPIRY_HOURS = app_config.PASSWORD_RESET_EXPIRY_HOURS

TRAVEL_REQUEST_EXPIRY_HOURS = app_config.TRAVEL_REQUEST_EXPIRY_HOURS
MAX_ACTIVE_TRAVEL_REQUESTS = app_config.MAX_ACTIVE_TRAVEL_REQUESTS
MAX_TRAVEL_REQUESTS_PER_DAY = app_config.MAX_TRAVEL_REQUESTS_PER_DAY
ALLOW_EDIT_AFTER_MATCH = app_config.ALLOW_EDIT_AFTER_MATCH

DEFAULT_MATCH_WINDOW_MINUTES = app_config.DEFAULT_MATCH_WINDOW_MINUTES
MAX_MATCH_DISTANCE_METERS = app_config.MAX_MATCH_DISTANCE_METERS
MAX_MATCH_RESULTS = app_config.MAX_MATCH_RESULTS

NOTIFICATION_RETENTION_DAYS = app_config.NOTIFICATION_RETENTION_DAYS
MAX_NOTIFICATIONS_PER_USER = app_config.MAX_NOTIFICATIONS_PER_USER
AUTO_MARK_READ_AFTER_DAYS = app_config.AUTO_MARK_READ_AFTER_DAYS

EMAIL_VERIFICATION_EXPIRY_HOURS = app_config.EMAIL_VERIFICATION_EXPIRY_HOURS
EMAIL_RESEND_DELAY_SECONDS = app_config.EMAIL_RESEND_DELAY_SECONDS
DEFAULT_FROM_EMAIL = app_config.DEFAULT_FROM_EMAIL
EMAIL_SUBJECT_PREFIX = app_config.EMAIL_SUBJECT_PREFIX

DEFAULT_PAGE_SIZE = app_config.DEFAULT_PAGE_SIZE
MAX_PAGE_SIZE = app_config.MAX_PAGE_SIZE
DEFAULT_ORDERING = app_config.DEFAULT_ORDERING

LOGIN_RATE_LIMIT = app_config.LOGIN_RATE_LIMIT
REGISTER_RATE_LIMIT = app_config.REGISTER_RATE_LIMIT
OTP_RATE_LIMIT = app_config.OTP_RATE_LIMIT
API_RATE_LIMIT = app_config.API_RATE_LIMIT

TRAVEL_REQUEST_EXPIRY_CHECK_INTERVAL = app_config.TRAVEL_REQUEST_EXPIRY_CHECK_INTERVAL
OTP_CLEANUP_INTERVAL = app_config.OTP_CLEANUP_INTERVAL
NOTIFICATION_CLEANUP_INTERVAL = app_config.NOTIFICATION_CLEANUP_INTERVAL
HEALTH_CHECK_INTERVAL = app_config.HEALTH_CHECK_INTERVAL
OTP_RETENTION_HOURS = app_config.OTP_RETENTION_HOURS

FEATURE_FLAGS = app_config.FEATURE_FLAGS


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    'apps.accounts.apps.AccountsConfig',
    'apps.destinations.apps.DestinationsConfig',
    'apps.travel_requests.apps.TravelRequestsConfig',
    'apps.dashboard.apps.DashboardConfig',
    'apps.notifications.apps.NotificationsConfig',
    'apps.auto_drivers.apps.AutoDriversConfig',
    'apps.admin_portal.apps.AdminPortalConfig',
    'apps.ride_history.apps.RideHistoryConfig',
    'apps.chat.apps.ChatConfig',
]

ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'apps.common.middleware.SecurityHeadersMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.common.middleware.RequestLoggingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS — restrict to known frontend origins
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:5173',
    'http://127.0.0.1:5173',
])

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
        'CONN_MAX_AGE': env.int('CONN_MAX_AGE', default=600),
        'CONN_HEALTH_CHECKS': True,
    }
}

# Caching & Throttling Configuration (Redis in production, LocMemCache in local/testing)
if env.bool('USE_REDIS_CACHE', default=False):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/0'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'automacha-cache',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Django REST Framework
_RENDERER_CLASSES = ['rest_framework.renderers.JSONRenderer']
if DEBUG:
    _RENDERER_CLASSES.append('rest_framework.renderers.BrowsableAPIRenderer')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': _RENDERER_CLASSES,
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '120/minute',
    },
}

# Custom Authentication Backends (Allows login with Username, Roll Number, or Institute Email)
AUTHENTICATION_BACKENDS = [
    'apps.accounts.authentication.MultiFieldModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# SimpleJWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Production Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'


# Centralized Log Directory
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOG_LEVEL = env('LOG_LEVEL', default='INFO' if not DEBUG else 'DEBUG')

# Centralized Structured Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_context': {
            '()': 'apps.common.logging.RequestContextFilter',
        },
    },
    'formatters': {
        'structured': {
            '()': 'apps.common.logging.StructuredFormatter',
        },
        'simple': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['request_context'],
            'formatter': 'structured',
            'level': 'DEBUG',
        },
        'application_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'application.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'filters': ['request_context'],
            'formatter': 'structured',
            'level': 'INFO',
        },
        'authentication_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'authentication.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'filters': ['request_context'],
            'formatter': 'structured',
            'level': 'INFO',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'security.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'filters': ['request_context'],
            'formatter': 'structured',
            'level': 'WARNING',
        },
        'background_tasks_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'background_tasks.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'filters': ['request_context'],
            'formatter': 'structured',
            'level': 'INFO',
        },
        'errors_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'filters': ['request_context'],
            'formatter': 'structured',
            'level': 'ERROR',
        },
    },
    'root': {
        'handlers': ['console', 'application_file', 'errors_file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'application_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api.request': {
            'handlers': ['console', 'application_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'auth': {
            'handlers': ['console', 'authentication_file', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['console', 'security_file', 'errors_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'database': {
            'handlers': ['console', 'errors_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'application_file', 'errors_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'apps.background_tasks': {
            'handlers': ['console', 'background_tasks_file', 'errors_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Celery Configuration
REDIS_URL = env('REDIS_URL', default='redis://127.0.0.1:6379/0')
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=not env.bool('USE_REDIS_CACHE', default=False))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 5 * 60

# Background Job Retention & Expiry Settings
TRAVEL_REQUEST_EXPIRY_HOURS = env.int('TRAVEL_REQUEST_EXPIRY_HOURS', default=24)
NOTIFICATION_RETENTION_DAYS = env.int('NOTIFICATION_RETENTION_DAYS', default=30)
OTP_RETENTION_HOURS = env.int('OTP_RETENTION_HOURS', default=1)
HEALTH_CHECK_INTERVAL = env.int('HEALTH_CHECK_INTERVAL', default=3600)

# Celery Beat Periodic Tasks Schedule
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'expire-travel-requests': {
        'task': 'apps.travel_requests.tasks.expire_travel_requests_task',
        'schedule': crontab(minute='*/5'),
    },
    'delete-expired-otps': {
        'task': 'apps.accounts.tasks.cleanup_expired_otps_task',
        'schedule': crontab(minute=0, hour='*'),
    },
    'delete-old-notifications': {
        'task': 'apps.notifications.tasks.cleanup_old_notifications_task',
        'schedule': crontab(minute=0, hour=0),
    },
    'refresh-dashboard-cache': {
        'task': 'apps.dashboard.tasks.refresh_dashboard_cache_task',
        'schedule': crontab(minute='*/1'),
    },
    'health-check-task': {
        'task': 'apps.common.tasks.system_health_check_task',
        'schedule': crontab(minute=0, hour='*'),
    },
}

