# Generated by Django 5.2.16 on 2026-07-27 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the notification.', max_length=255)),
                ('message', models.TextField(help_text='Detailed message content.')),
                ('notification_type', models.CharField(choices=[('RIDE_SHARE_REQUEST_RECEIVED', 'Ride Share Request Received'), ('RIDE_SHARE_REQUEST_ACCEPTED', 'Ride Share Request Accepted'), ('RIDE_SHARE_REQUEST_DECLINED', 'Ride Share Request Declined'), ('TRAVEL_REQUEST_EXPIRED', 'Travel Request Expired'), ('NEW_MATCH_FOUND', 'New Match Found')], help_text='Type of notification event.', max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of the related object (e.g., TravelRequest or RideShareRequest ID).', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read by the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user receiving this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
