# Generated by Django 5.2.16 on 2026-07-29 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_user_read',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_user_created',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='idx_notif_user_read_created'),
        ),
    ]
