# Generated by Django 5.2.16 on 2026-07-28 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Name/type of the administrative action (e.g. USER_DISABLED, DRIVER_APPROVED).', max_length=100)),
                ('affected_object', models.CharField(help_text='Identifier or label of the target object affected (e.g. User #12, TravelRequest #4).', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context or state changes associated with this audit event.')),
                ('request_id', models.CharField(blank=True, default='', help_text='X-Request-ID correlated with the HTTP request.', max_length=100)),
                ('ip_address', models.CharField(blank=True, default='', help_text='IP address of the client triggering the admin action.', max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='The admin/staff user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='idx_audit_action'), models.Index(fields=['-timestamp'], name='idx_audit_timestamp'), models.Index(fields=['admin_user', '-timestamp'], name='idx_audit_user_ts')],
            },
        ),
    ]
