# Generated by Django 5.2.16 on 2026-07-26 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('TO_CAMPUS', 'To Campus'), ('FROM_CAMPUS', 'From Campus')], help_text='Direction of travel (To Campus or From Campus).', max_length=20)),
                ('travel_datetime', models.DateTimeField(help_text='Scheduled date and time of departure/arrival.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', help_text='Current status of the travel request.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(help_text='The approved outing or travel destination.', on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='destinations.destination')),
                ('user', models.ForeignKey(help_text='The student who created this travel request.', on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Request',
                'verbose_name_plural': 'Travel Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
