# Generated by Django 5.2.16 on 2026-07-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='OPEN', help_text='Current status of the travel request.', max_length=20),
        ),
    ]
