# Generated by Django 5.2.16 on 2026-07-28 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_idx_destination_active_name'),
        ('travel_requests', '0002_alter_travelrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['status'], name='idx_travelreq_status'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['travel_datetime'], name='idx_travelreq_datetime'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['user', 'status'], name='idx_travelreq_user_status'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['status', 'destination', 'direction'], name='idx_travelreq_match'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['status', 'travel_datetime'], name='idx_travelreq_status_dt'),
        ),
    ]
