# Generated by Django 5.2.16 on 2026-07-29 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_idx_destination_active_name'),
        ('travel_requests', '0003_travelrequest_idx_travelreq_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='travelrequest',
            name='idx_travelreq_match',
        ),
        migrations.RemoveIndex(
            model_name='travelrequest',
            name='idx_travelreq_status_dt',
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['status', 'destination', 'direction', 'travel_datetime'], name='idx_travelreq_match_full'),
        ),
    ]
