# Generated by Django 5.2.16 on 2026-07-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0004_remove_travelrequest_idx_travelreq_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Soft delete flag to hide the request from the user's view."),
        ),
    ]
