# Generated by Django 5.2.16 on 2026-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0005_travelrequest_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='seats_available',
            field=models.IntegerField(default=1, help_text='Number of available seats for this ride.'),
        ),
    ]
