# Generated by Django 5.2.16 on 2026-07-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic year (e.g. 1st Year, 2nd Year, etc.).', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating score.', max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short user biography.', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full display name of the user.', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when profile was last updated.'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture.', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_completed_rides',
            field=models.PositiveIntegerField(default=0, help_text='Count of completed rides.'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings received.'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_ride_shares',
            field=models.PositiveIntegerField(default=0, help_text='Total ride shares joined or offered.'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_travel_requests',
            field=models.PositiveIntegerField(default=0, help_text='Total travel requests created.'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Verification'), ('unverified', 'Unverified')], default='verified', help_text='Account verification status.', max_length=20),
        ),
    ]
