# Generated by Django 5.2.16 on 2026-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the travel destination.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or details about the destination.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this destination is available for travel requests.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
            },
        ),
    ]
