# Generated by Django 5.2.16 on 2026-07-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_active', 'name'], name='idx_destination_active_name'),
        ),
    ]
