# Generated by Django 5.2.16 on 2026-08-03 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_remove_campus_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional custom label (e.g., 'Home', 'Work').", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(help_text='The destination being saved.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='destinations.destination')),
                ('user', models.ForeignKey(help_text='The user who saved this destination.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Destination',
                'verbose_name_plural': 'Saved Destinations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'destination')},
            },
        ),
    ]
