/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope;

// Take over control immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by the build process.
// `self.__WB_MANIFEST` is injected by vite-plugin-pwa during the build.
precacheAndRoute(self.__WB_MANIFEST);

// ---------------------------------------------------------
// ROUTING STRATEGIES
// ---------------------------------------------------------

// 1. API Requests -> Network First
// We want fresh data for API calls, but fallback to cache if offline.
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'automacha-api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// 2. Static Assets (Images, Icons) -> Cache First
// We can cache these for a long time as they don't change often.
registerRoute(
  ({ request, url }) => request.destination === 'image' || url.pathname.endsWith('.png') || url.pathname.endsWith('.svg'),
  new CacheFirst({
    cacheName: 'automacha-images',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// 3. Fonts and Styles -> Stale While Revalidate
registerRoute(
  ({ request, url }) => request.destination === 'font' || request.destination === 'style' || url.href.includes('fonts.googleapis.com') || url.href.includes('fonts.gstatic.com'),
  new StaleWhileRevalidate({
    cacheName: 'automacha-fonts-styles',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// 4. App Shell (Navigation) -> Fallback to index.html
// This ensures that our single-page application routes work offline.
try {
  // Try to set up a navigation route to always return index.html for navigation requests
  const handler = createHandlerBoundToURL('/index.html');
  const navigationRoute = new NavigationRoute(handler, {
    denylist: [
      new RegExp('/api/.*'), // Skip API routes
    ],
  });
  registerRoute(navigationRoute);
} catch (e) {
  console.log('Error creating navigation route', e);
}

// ---------------------------------------------------------
// PUSH NOTIFICATIONS (Architecture placeholder)
// ---------------------------------------------------------
self.addEventListener('push', (event) => {
  if (event.data) {
    const data = event.data.json();
    const title = data.title || 'AutoMacha';
    const options = {
      body: data.body || 'You have a new notification.',
      icon: '/pwa-192x192.png',
      badge: '/pwa-72x72.png',
      data: data.url || '/',
    };

    event.waitUntil(self.registration.showNotification(title, options));
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  // Open the app to the appropriate URL
  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((clientList) => {
      const urlToOpen = new URL(event.notification.data, self.location.origin).href;

      // If a window is already open, focus it and navigate
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
