# Generated by Django 5.2.16 on 2026-07-29 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_requests', '0003_travelrequest_idx_travelreq_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Active status. Becomes False when ride is completed or cancelled.')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when the room was closed to new messages.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The travel request owner/requester.', on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='The accepted ride partner.', on_delete=django.db.models.deletion.CASCADE, related_name='joined_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('ride_request', models.OneToOneField(help_text='The travel request for which this chat room is established.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='travel_requests.travelrequest')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Text message or system event description.')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('SYSTEM', 'System Event'), ('IMAGE', 'Image Attachment'), ('LOCATION', 'Live Location'), ('VOICE', 'Voice Message')], default='TEXT', help_text='Type of message (TEXT, SYSTEM, IMAGE, etc.).', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this message.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, help_text='The user who sent this message. Null for system messages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(help_text='The chat room this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_active'], name='idx_chatroom_active'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_by', 'is_active'], name='idx_chatroom_owner_active'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['partner', 'is_active'], name='idx_chatroom_part_active'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room', 'created_at'], name='idx_chatmsg_room_created'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room', 'is_read'], name='idx_chatmsg_room_read'),
        ),
    ]
