# Generated by Django 5.2.16 on 2026-07-29 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, help_text='Users who have deleted this message for themselves.', related_name='deleted_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted_everyone',
            field=models.BooleanField(default=False, help_text='True if soft deleted for all participants.'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='iv',
            field=models.CharField(blank=True, help_text='Base64 IV for AES-256-GCM encryption.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='cleared_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have cleared chat history for themselves.', related_name='cleared_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(help_text='Encrypted text payload or system event description.'),
        ),
    ]
