# Generated by Django 5.2.16 on 2026-07-29 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_deleted_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room', 'sender', 'is_read'], name='idx_chatmsg_room_sndr_read'),
        ),
    ]
