# Generated by Django 5.2.16 on 2026-07-30 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_idx_chatmsg_room_sndr_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, help_text='Users who have completely hidden this chat room from their inbox.', related_name='deleted_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
