# Generated by Django 5.2.16 on 2026-08-05 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_deleted_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatroom',
            name='idx_chatroom_part_active',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='partner',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='The accepted ride partners.', related_name='joined_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
