# Generated by Django 5.2.16 on 2026-08-17 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatroom_idx_chatroom_part_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='archived_for',
            field=models.ManyToManyField(blank=True, help_text='Users who have archived this chat room.', related_name='archived_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
