# Generated by Django 5.2.16 on 2026-07-29 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_requests', '0003_travelrequest_idx_travelreq_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_request_id', models.IntegerField(blank=True, help_text='Optional reference ID for the ride share request/notification.', null=True)),
                ('destination', models.CharField(help_text='Snapshot of the travel destination at time of ride.', max_length=255)),
                ('pickup_location', models.CharField(default='Campus', help_text='Snapshot of pickup or starting location.', max_length=255)),
                ('departure_time', models.DateTimeField(help_text='Scheduled departure date and time.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the ride reached completed/cancelled/expired status.', null=True)),
                ('ride_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], help_text='Status of the recorded ride history entry.', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='User rating for this ride (1 to 5 stars).', null=True)),
                ('review_text', models.TextField(blank=True, default='', help_text='Optional feedback or review comments.')),
                ('achievements', models.JSONField(blank=True, default=dict, help_text='Future analytics and milestone achievement tags.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride_partner', models.ForeignKey(blank=True, help_text='The ride partner/companion for this ride, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_ride_histories', to=settings.AUTH_USER_MODEL)),
                ('travel_request', models.ForeignKey(blank=True, help_text='Reference to original travel request if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_histories', to='travel_requests.travelrequest')),
                ('user', models.ForeignKey(help_text='The user for whom this ride activity is recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='ride_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ride History',
                'verbose_name_plural': 'Ride Histories',
                'ordering': ['-departure_time', '-created_at'],
                'indexes': [models.Index(fields=['user', 'ride_status'], name='idx_ridehist_user_status'), models.Index(fields=['user', '-departure_time'], name='idx_ridehist_user_deptime'), models.Index(fields=['user', 'destination'], name='idx_ridehist_user_dest')],
                'constraints': [models.UniqueConstraint(fields=('user', 'travel_request', 'ride_status'), name='unique_user_travelreq_status_history')],
            },
        ),
    ]
