# Generated by Django 5.2.16 on 2026-07-28 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the auto driver.', max_length=255)),
                ('phone_number', models.CharField(help_text='Unique 10-digit mobile phone number of the driver.', max_length=15, unique=True)),
                ('vehicle_number', models.CharField(blank=True, default='', help_text='Optional vehicle registration / auto number (e.g. AP 39 AB 1234).', max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes or operating route details.')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the driver record has been verified and approved by admin.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the driver is active and visible in the directory.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The student user who suggested this driver (null if added directly by admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_auto_drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto Driver',
                'verbose_name_plural': 'Auto Drivers',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['is_verified', 'is_active'], name='idx_driver_verified_active'), models.Index(fields=['phone_number'], name='idx_driver_phone'), models.Index(fields=['full_name'], name='idx_driver_name')],
            },
        ),
    ]
